### PR TITLE
Add simple test

### PR DESCRIPTION
**Pull request by ZYSzys**
Add simple test inspired by the `Usage example` from README.😅

### CODE REVIEW

**Comment by bvaughn** [comment]
I'm not sure how I feel about tests in the case of a tiny lib like this. I think they're probably valuable, but only if they're low friction. I'm not familiar with `ava` (pretty sure I've never used it on anything before) so it wouldn't be low friction enough for me. On the other hand, I would consider using something like Jest.

**Comment by ZYSzys** [comment]
Using jest also sounds great , I’ll try to test it using jest.

**Comment by ZYSzys** [comment]
I did a simple test like the case in README.md without using any testing framework since as you said
> a tiny lib like this. I think they're probably valuable, but only if they're low friction.

PTAL.

**Comment by bvaughn** [comment]
Hm, interesting.

I'm not sure what value this test is providing– other than a really basic sanity check that the code doesn't runtime error. But the test doesn't verify that the code completes successfully, or logs anything to the console, or accepts the `storagePath` param you specified, etc.

**Comment by ZYSzys** [comment]
Thanks for your reply. But sorry for my poor ability now.😅

I'll try to make some useful tests if possible, close this for now.

**Comment by bvaughn** [comment]
Eee, sorry for the slow response. Got distracted with other work things.

No worries! I appreciate the effort here. Let's talk more if you think of new testing ideas.

**Pull request closed without merging**
